#controllers:
#    resource: '../src/Controller/'
#    type: annotation
#    prefix: /{_locale}
#    requirements:
#        _locale: '%app_locales%'
#    defaults:
#        _locale: 'en'
controllers:
    resource: '../src/Controller/'
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
    path: /{_locale}
    controller: App\Controller\DefaultController::index

fos_user_security:
    prefix: /{_locale}
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"